# Generated by Django 4.2.5 on 2023-09-16 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='No Title Provided', max_length=40, verbose_name='Post Title')),
                ('body', models.TextField(blank=True, default='No Content Provided', verbose_name='Post Body')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='date the post was last updated')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Post Image')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
    ]
